parameters:
    ite_doctrine_extra.proxy_dir: %kernel.cache_dir%/ite_doctrine_extra/proxy
    ite_doctrine_extra.proxy_factory.class: ITE\DoctrineExtraBundle\Proxy\ProxyFactory
    ite_doctrine_extra.interceptor_method_factory.class: ITE\DoctrineExtraBundle\Proxy\InterceptorMethodFactory

services:
    ite_doctrine_extra.proxy_factory:
        class: %ite_doctrine_extra.proxy_factory.class%
        arguments: [ @filesystem, %ite_doctrine_extra.proxy_dir% ]

    ite_doctrine_extra.interceptor_method_factory:
        class: %ite_doctrine_extra.interceptor_method_factory.class%
        arguments: [ @service_container ]